export const createEmptyShopFormData = () => ({
  _id: "",
  name: "",
  companyCode: "",
  deletedFiles: [],
  closedDates: [],
  description: "",
  about: "",
  categories: [],
  tags: [],
  logo: { file: [], isAdd: 0, isDeleted: 0 },
  coverImage: { file: [], isAdd: 0, isDeleted: 0 },
  ratings: {
    average: 0,
    total: 0,
  },
  gallery: [],
  location: {
    address: "",
    city: "",
    state: "",
    postalCode: "",
    country: "",
    coordinates: [0, 0],
  },
  multipleLocations: [
    {
      address: "",
      city: "",
      state: "",
      postalCode: "",
      country: "",
      coordinates: [0, 0],
    },
  ],
  contactInfo: {
    phone: "",
    email: "",
    website: "",
    socialMedia: {
      instagram: "",
      facebook: "",
      twitter: "",
      linkedin: "",
      youtube: "",
    },
  },
  operatingHours: [
    { day: "Monday", open: "09:00", close: "18:00" },
    { day: "Tuesday", open: "09:00", close: "18:00" },
    { day: "Wednesday", open: "09:00", close: "18:00" },
    { day: "Thursday", open: "09:00", close: "18:00" },
    { day: "Friday", open: "09:00", close: "18:00" },
    { day: "Saturday", open: "", close: "" },
    { day: "Sunday", open: "", close: "" },
  ],
  status: "active",
  gstNumber: "",
  bankDetails: {
    accountHolderName: "",
    accountNumber: "",
    ifscCode: "",
    bankName: "",
  },
  returnPolicy: "",
  paymentMethods: [],
});

export const dummyData = createEmptyShopFormData();
